package org.app.dechar.modelo;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import org.app.dechar.modelo.Palabra;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PALABRA.
*/
public class PalabraDao extends AbstractDao<Palabra, Long> {

    public static final String TABLENAME = "PALABRA";

    /**
     * Properties of entity Palabra.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nombre = new Property(1, String.class, "nombre", false, "NOMBRE");
        public final static Property Descripcion = new Property(2, String.class, "descripcion", false, "DESCRIPCION");
        public final static Property IdCategoriaPalabra = new Property(3, Long.class, "idCategoriaPalabra", false, "ID_CATEGORIA_PALABRA");
    };

    private Query<Palabra> categoria_PalabraQuery;

    public PalabraDao(DaoConfig config) {
        super(config);
    }
    
    public PalabraDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PALABRA' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NOMBRE' TEXT," + // 1: nombre
                "'DESCRIPCION' TEXT," + // 2: descripcion
                "'ID_CATEGORIA_PALABRA' INTEGER);"); // 3: idCategoriaPalabra
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PALABRA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Palabra entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String nombre = entity.getNombre();
        if (nombre != null) {
            stmt.bindString(2, nombre);
        }
 
        String descripcion = entity.getDescripcion();
        if (descripcion != null) {
            stmt.bindString(3, descripcion);
        }
 
        Long idCategoriaPalabra = entity.getIdCategoriaPalabra();
        if (idCategoriaPalabra != null) {
            stmt.bindLong(4, idCategoriaPalabra);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Palabra readEntity(Cursor cursor, int offset) {
        Palabra entity = new Palabra( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // nombre
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // descripcion
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // idCategoriaPalabra
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Palabra entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNombre(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDescripcion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIdCategoriaPalabra(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Palabra entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Palabra entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "Palabra" to-many relationship of Categoria. */
    public List<Palabra> _queryCategoria_Palabra(Long idCategoriaPalabra) {
        synchronized (this) {
            if (categoria_PalabraQuery == null) {
                QueryBuilder<Palabra> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdCategoriaPalabra.eq(null));
                categoria_PalabraQuery = queryBuilder.build();
            }
        }
        Query<Palabra> query = categoria_PalabraQuery.forCurrentThread();
        query.setParameter(0, idCategoriaPalabra);
        return query.list();
    }

}
