package org.app.dechar.modelo;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PALABRA.
 */
public class Palabra {

    private Long id;
    private String nombre;
    private String descripcion;
    private Long idCategoriaPalabra;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Palabra() {
    }

    public Palabra(Long id) {
        this.id = id;
    }

    public Palabra(Long id, String nombre, String descripcion, Long idCategoriaPalabra) {
        this.id = id;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.idCategoriaPalabra = idCategoriaPalabra;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Long getIdCategoriaPalabra() {
        return idCategoriaPalabra;
    }

    public void setIdCategoriaPalabra(Long idCategoriaPalabra) {
        this.idCategoriaPalabra = idCategoriaPalabra;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
