package org.app.dechar.modelo;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TIEMPO.
 */
public class Tiempo {

    private Long id;
    private Integer segundos;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Tiempo() {
    }

    public Tiempo(Long id) {
        this.id = id;
    }

    public Tiempo(Long id, Integer segundos) {
        this.id = id;
        this.segundos = segundos;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSegundos() {
        return segundos;
    }

    public void setSegundos(Integer segundos) {
        this.segundos = segundos;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
